#!/usr/bin/env python3
"""Generate qemu/cryptostore_kat.h from the published test vectors (SR-34).

Vectors are parsed from the original documents, never typed by hand:
  RFC 5869 (HKDF-SHA256, test cases 1-3)       https://www.rfc-editor.org/rfc/rfc5869.txt
  RFC 7914 section 11 (PBKDF2-HMAC-SHA256)     https://www.rfc-editor.org/rfc/rfc7914.txt
  RFC 4231 (HMAC-SHA256, test cases 1, 2, 6)   https://www.rfc-editor.org/rfc/rfc4231.txt
  IEEE 1619-2007 XTS-AES-256 vector 10, as carried in Linux crypto/testmgr.h
                                               https://raw.githubusercontent.com/torvalds/linux/master/crypto/testmgr.h

Usage: gen-cryptostore-kat.py DIR_WITH_DOWNLOADS > qemu/cryptostore_kat.h
"""
import re
import sys

d = sys.argv[1]


def hexbytes(s):
    return bytes.fromhex(re.sub(r"[^0-9a-fA-F]", "", s))


def rfc_field(block, name):
    """Hex value of 'name = 0x....' possibly continued on indented lines."""
    m = re.search(r"^\s*" + re.escape(name) + r"\s*=\s*(.*?)(?=^\s*\w[\w-]*\s*=|\Z)",
                  block, re.M | re.S)
    val = m.group(1)
    if "(0 octets)" in val:
        return b""
    val = re.sub(r"\(\d+ (octets|bytes)\)", "", val)
    val = re.sub(r"\(\".*?\"\)", "", val)
    return hexbytes(val.replace("0x", ""))


def strip_pages(text):
    """Drop RFC page footers/headers and form feeds (line based)."""
    keep = [ln for ln in text.split("\n")
            if "[Page " not in ln and not re.match(r"RFC \d+ ", ln) and ln.strip() != "\f"]
    return "\n".join(keep).replace("\f", "")


def section(text, start, end):
    """Body between two headings that start a line (skips the table of contents)."""
    i = re.search(r"^" + re.escape(start), text, re.M).start()
    j = re.compile(r"^" + re.escape(end), re.M).search(text, i + len(start)).start()
    return text[i:j]


out = []


def carr(name, b):
    body = ",".join(f"0x{x:02x}" for x in b) if b else "0"
    return (f"static const uint8_t {name}[{max(len(b), 1)}] = {{{body}}};\n"
            f"#define {name.upper()}_LEN {len(b)}")


# HKDF (RFC 5869 A.1-A.3)
r5869 = open(f"{d}/rfc5869.txt").read()
hkdf = []
for n, (a, b) in enumerate([("A.1.  Test Case 1", "A.2.  Test Case 2"),
                            ("A.2.  Test Case 2", "A.3.  Test Case 3"),
                            ("A.3.  Test Case 3", "A.4.  Test Case 4")], 1):
    blk = strip_pages(section(r5869, a, b))
    v = {k: rfc_field(blk, k) for k in ("IKM", "salt", "info", "PRK", "OKM")}
    L = int(re.search(r"L\s*=\s*(\d+)", blk).group(1))
    assert len(v["OKM"]) == L and len(v["PRK"]) == 32, n
    for k, val in v.items():
        out.append(carr(f"kat_hkdf{n}_{k.lower()}", val))
    hkdf.append((n, v))

# PBKDF2-HMAC-SHA256 (RFC 7914 section 11)
r7914 = open(f"{d}/rfc7914.txt").read()
sec = section(r7914, "11.  Test Vectors for PBKDF2 with HMAC-SHA-256", "12.  Test Vectors for scrypt")
pb = []
for n, m in enumerate(re.finditer(
        r'PBKDF2-HMAC-SHA-256 \(P="(.*?)", S="(.*?)",\s*c=(\d+), dkLen=(\d+)\) =\s*((?:[0-9a-f]{2}\s+)+)', sec), 1):
    P, S, c, dklen, hx = m.groups()
    dk = hexbytes(hx)
    assert len(dk) == int(dklen)
    out.append(carr(f"kat_pbkdf2_{n}_dk", dk))
    pb.append((n, P, S, int(c), len(dk)))
assert len(pb) == 2

# HMAC-SHA256 (RFC 4231 4.2, 4.3, 4.7)
r4231 = open(f"{d}/rfc4231.txt").read()
hm = []
for n, (a, b) in [(1, ("4.2.  Test Case 1", "4.3.  Test Case 2")),
                  (2, ("4.3.  Test Case 2", "4.4.  Test Case 3")),
                  (6, ("4.7.  Test Case 6", "4.8.  Test Case 7"))]:
    blk = strip_pages(section(r4231, a, b))
    key = rfc_field(blk, "Key")
    data = rfc_field(blk, "Data")
    mac = rfc_field(blk, "HMAC-SHA-256")
    assert len(mac) == 32, n
    out.append(carr(f"kat_hmac{n}_key", key))
    out.append(carr(f"kat_hmac{n}_data", data))
    out.append(carr(f"kat_hmac{n}_mac", mac))
    hm.append(n)

# XTS-AES-256 (IEEE 1619-2007 vector 10, from Linux testmgr.h)
tm = open(f"{d}/testmgr.h").read()
blk = tm[tm.index("/* XTS-AES 10, XTS-AES-256, data unit 512 bytes */"):]
blk = blk[:blk.index(".len\t= 512")]


def tm_field(name):
    f = re.search(r"\." + name + r'\s*=\s*((?:"[^"]*"\s*)+)', blk).group(1)
    return bytes(int(h, 16) for h in re.findall(r"\\x([0-9a-fA-F]{2})", f))


xts = {k: tm_field(k) for k in ("key", "iv", "ptext", "ctext")}
assert [len(xts[k]) for k in ("key", "iv", "ptext", "ctext")] == [64, 16, 512, 512]
for k, v in xts.items():
    out.append(carr(f"kat_xts10_{k}", v))

print("/* Generated by tools/gen-cryptostore-kat.py from the published documents. Do not edit. */")
print("/* RFC 5869 A.1-A.3, RFC 7914 s11, RFC 4231 4.2/4.3/4.7, IEEE 1619-2007 vector 10. */")
print("#ifndef CRYPTOSTORE_KAT_H\n#define CRYPTOSTORE_KAT_H\n")
print("\n".join(out))
print()
for n, P, S, c, dl in pb:
    print(f'#define KAT_PBKDF2_{n}_P "{P}"\n#define KAT_PBKDF2_{n}_S "{S}"\n#define KAT_PBKDF2_{n}_C {c}')
print("\n#endif")
